name: feature_cli
description: CLI to generate Flutter feature (clean architecture + bloc enum)
version: 0.1.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  recase: ^4.1.0
  args: ^2.4.0
  

executables:
  feature_cli: feature_cli
